### ISSUE TITLE
无法保存灰度图像

### ISSUE THREAD

**Issue by DXQer** [JaySon-Huang/pyjpegtbx#18]
在mode_DCT的情况下，使用save()函数进行灰度jpeg图像保存的时候，会有以下报错信息:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./pyjpegtbx-master/pyjpegtbx/__init__.py", line 311, in save
  File "./pyjpegtbx-master/pyjpegtbx/__init__.py", line 234, in __setcinfo
IndexError: list index out of range

**Comment by JaySon-Huang** [comment]
不知道你具体是如何使用的？ @DXQer 
是使用 mode_DCT 从零创建一个新的对象后，自己填充数据，然后保存。
还是使用 mode_DCT 读取一个 jpeg 文件，做修改，然后再进行保存？

**Comment by DXQer** [comment]
> 不知道你具体是如何使用的？ @DXQer
> 是使用 mode_DCT 从零创建一个新的对象后，自己填充数据，然后保存。
> 还是使用 mode_DCT 读取一个 jpeg 文件，做修改，然后再进行保存？

是直接使用mode_DCT读取一个JPEG文件，然后做修改（或者不修改），进行保存时出的错误
